FROM openjdk:8u322-jre-slim-bullseye
WORKDIR /danmuji
RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apt update && apt install unzip wget curl -y \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && wget https://raw.githubusercontent.com/zzcabc/Docker_Buildx_Danmuji/main/start.sh \
    && chmod +x start.sh \
    && mkdir Danmuji_log && mkdir guardFile && mkdir log \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*    
EXPOSE 23333
ENV JAVA_OPTS=""
ENTRYPOINT ["./start.sh"]