FROM openjdk:11.0.1-jre-slim

WORKDIR /danmuji
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
COPY Bilibili_Danmuji/danmuji.jar /danmuji/danmuji.jar
EXPOSE 23333
VOLUME /danmuji/Danmuji_log /danmuji/guardFile /danmuji/log
ENTRYPOINT ["java", "-jar", "danmuji.jar"]