FROM openjdk:17-windowsservercore-1809
WORKDIR /danmuji
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
COPY Bilibili_Danmuji/danmuji.jar /danmuji/danmuji.jar
EXPOSE 23333
VOLUME /danmuji/Danmuji_log /danmuji/guardFile /danmuji/log /danmuji/DanmujiProfile
ENV JAVA_OPTS=""
ENTRYPOINT ["sh","-c","java ${JAVA_OPTS} -jar danmuji.jar"]